headTitle: "Frank"
# 网页上网站的描述
# description: "Welcome to my blog"
# 作者名
author: "Frank"
mainSections: "posts"
# 一些链接地址，我是倾向于这个部分也不加的，如果要加可以放在页面的最下方，这样子 tag、categories、home、about 等页面都不需要了，保持最简洁
# socials:
#   - name: "About Me"
#     link: "https://joway.io"
#   - name: "Github"
#     link: "https://github.com/joway"

twitterCards: true
categories: 