
# base config
baseURL: "https://sunyunxian.github.io/blog/"
CanonifyURLs: true # fix suburl error
theme: "yinyang"
title: "场上没有别人 - No Others " # tab display
LanguageCode: "en-us" # language
DefaultContentLanguage: "cn" # default display which language posts
enableRobotsTXT: true
buildDrafts: false
disablePathToLower: true
#-----------------------------------------------
author:
  name: "_Frank"
  homepage: "https://sunyunxian.github.io/sunyunxian/"
  # blog_homepage: ""
#-----------------------------------------------
languages:
  # en:
  #   contentDir: "content/en/"
  #   languageName: "English"
  #   weight: 1
  cn:
    contentDir: "content/cn/"
    languageName: "简体中文"
    weight: 2
# ---------------------------------------------
markup:
  highlight:
    guessSyntax: true
    noClasses: true
    # style: "tango"
    # tabWidth: 2
#----------------------------------------------
params:
  # headTitle: "Frank"
  description: "欢迎来到场上没有别人博客，分享数字产品或科学方法的一些思考和实践，提升工作效率和生活品质"
  mainSections: "posts" # # post path
  lazyImage: true
  disqus: "https-sunyunxian-github-io-blog" # disqus account name

  # extraCSSFiles: ["css/foo.css", "css/bar.css"]
  extraHead: "<script async src: 'https://www.googletagmanager.com/gtag/js?id=UA-215882903-1'></script>"
  # postHeaderContent: ""
  # postFooterContent: "<br/><br/><p>Subscribe：<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"
  socials:
    - 
      name: "Home"
      link: "/"
    - 
      name: "About"
      link: "posts/about_me/"
    - 
      name: "Email"
      link: "mailto:personal.sunyunxian+blog@gmail.com"

  twitterCards: true
#--------------------------------------------
