# url 配置
baseURL: "https://sunyunxian.github.io/blog"
# 网站语言
LanguageCode: "zh"
# 默认语言，如果你有多语言的需求可以配置此项
DefaultContentLanguage: "zh"
author:
  # 显示文章的作者
  name: "SunYunxian"
  # 这个是点击作者的按钮，直接跳转自己的主页
  homepage: "https://sunyunxian.github.io/"
  # blog 主页的左上角的跳转地址，
  blog_homepage: "/blog"
